### ISSUE TITLE
Unrecognized options "groups, serialize_null" under "fazland_elastica.serializer"

### ISSUE THREAD

**Issue by skonsoft** [fazland/FazlandElasticaBundle#2]
Hello,

I followed documentation as described [here](https://github.com/fazland/FazlandElasticaBundle/blob/master/Resources/doc/serializer.md) 

When i put jms serializer as global option, i got this error:

```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]      
  Unrecognized options "groups, serialize_null" under "fazland_elastica.serializer"
```

Here is my config:

```
fazland_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer:
         groups: [elastica, Default]
         serialize_null: true
    indexes:
        app:
            index_name: %database_name% #We use the database name as index 
            types:
                country:
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  "\\Skonsoft\\ModelBundle\\Entity\\Country"
                        provider: ~

```
